INSERT INTO clients (name, city, email) VALUES ('Tammy Cruz', 'Málaga', 'tammy.cruz@example.com');
INSERT INTO clients (name, city, email) VALUES ('Elba Salcedo', 'East Lee', 'elba.salcedo@example.com');
INSERT INTO clients (name, city, email) VALUES ('Erika Martin', 'Garciatown', 'erika.martin@example.com');
INSERT INTO clients (name, city, email) VALUES ('Nicole Watson', 'Teruel', 'nicole.watson@example.com');
INSERT INTO clients (name, city, email) VALUES ('Ezequiel Sarabia', 'Jenniferfort', 'ezequiel.sarabia@example.com');
INSERT INTO clients (name, city, email) VALUES ('Kike Rolón', 'San Claudia los bajos', 'kike.rolón@example.com');
INSERT INTO clients (name, city, email) VALUES ('Andrea Robinson', 'San Amalia de la Montaña', 'andrea.robinson@example.com');
INSERT INTO clients (name, city, email) VALUES ('Daniel Pelayo', 'North Alison', 'daniel.pelayo@example.com');
INSERT INTO clients (name, city, email) VALUES ('Elodia Tamayo', 'Marissaville', 'elodia.tamayo@example.com');
INSERT INTO clients (name, city, email) VALUES ('Josep Holland', 'Nueva Dinamarca', 'josep.holland@example.com');
INSERT INTO clients (name, city, email) VALUES ('Ciríaco Hernández', 'San Amanda los bajos', 'ciríaco.hernández@example.com');
INSERT INTO clients (name, city, email) VALUES ('Jose Francisco Lerma', 'East Shirleymouth', 'jose francisco.lerma@example.com');
INSERT INTO clients (name, city, email) VALUES ('Dana Ramón', 'Perkinston', 'dana.ramón@example.com');
INSERT INTO clients (name, city, email) VALUES ('Michael Tenorio', 'Castellón', 'michael.tenorio@example.com');
INSERT INTO clients (name, city, email) VALUES ('Carolina Padilla', 'Vanessashire', 'carolina.padilla@example.com');
INSERT INTO clients (name, city, email) VALUES ('Susana Merino', 'Robertview', 'susana.merino@example.com');
INSERT INTO clients (name, city, email) VALUES ('Lilia Yáñez', 'Cáceres', 'lilia.yáñez@example.com');
INSERT INTO clients (name, city, email) VALUES ('Salvador Summers', 'Nueva Saint Kitts y Nevis', 'salvador.summers@example.com');
INSERT INTO clients (name, city, email) VALUES ('Margarita Hawkins', 'Marieburgh', 'margarita.hawkins@example.com');
INSERT INTO clients (name, city, email) VALUES ('Ruben Ortiz', 'Navarra', 'ruben.ortiz@example.com');
INSERT INTO clients (name, city, email) VALUES ('Sheri Griffin', 'Barcelona', 'sheri.griffin@example.com');
INSERT INTO clients (name, city, email) VALUES ('Joseph Rogers', 'Lake Bonnie', 'joseph.rogers@example.com');
INSERT INTO clients (name, city, email) VALUES ('Christopher Vicens', 'Vieja Brasil', 'christopher.vicens@example.com');
INSERT INTO clients (name, city, email) VALUES ('Elena Thomas', 'New Vincent', 'elena.thomas@example.com');
INSERT INTO clients (name, city, email) VALUES ('Bernardino Barrett', 'Vizcaya', 'bernardino.barrett@example.com');
INSERT INTO clients (name, city, email) VALUES ('Adalberto Cantero', 'San Rufino los altos', 'adalberto.cantero@example.com');
INSERT INTO clients (name, city, email) VALUES ('Taylor Peláez', 'Barcelona', 'taylor.peláez@example.com');
INSERT INTO clients (name, city, email) VALUES ('Isaías Puerta', 'Cuenca', 'isaías.puerta@example.com');
INSERT INTO clients (name, city, email) VALUES ('Jessica Montez', 'Taylorville', 'jessica.montez@example.com');
INSERT INTO clients (name, city, email) VALUES ('Natasha Collins', 'East Kristin', 'natasha.collins@example.com');
INSERT INTO clients (name, city, email) VALUES ('Jerónimo Stevens', 'Valencia', 'jerónimo.stevens@example.com');
INSERT INTO clients (name, city, email) VALUES ('Emilio Mateo', 'Boydburgh', 'emilio.mateo@example.com');
INSERT INTO clients (name, city, email) VALUES ('Cándida Chavarría', 'Vieja Países Bajos', 'cándida.chavarría@example.com');
INSERT INTO clients (name, city, email) VALUES ('Soraya Tomas', 'Bowersmouth', 'soraya.tomas@example.com');
INSERT INTO clients (name, city, email) VALUES ('Susana Lopez', 'Baleares', 'susana.lopez@example.com');
INSERT INTO clients (name, city, email) VALUES ('Nélida Aragón', 'Nueva Omán', 'nélida.aragón@example.com');
INSERT INTO clients (name, city, email) VALUES ('George Calzada', 'San Celia los altos', 'george.calzada@example.com');
INSERT INTO clients (name, city, email) VALUES ('Inmaculada Brown', 'Ceuta', 'inmaculada.brown@example.com');
INSERT INTO clients (name, city, email) VALUES ('Ibán Nazario', 'Asturias', 'ibán.nazario@example.com');
